using System;
using System.Threading;

// Simple threading scenario:  Start a static method running
// on a second thread.
public class Singer
{
    Thread t;
    // The ThreadProc method is called when the thread starts.
    // It loops ten times, writing to the console and yielding 
    // the rest of its time slice each time, and then ends.
    public static void ShortMario()
    {
            Console.Beep(1318, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1318, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(1318, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(1046, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1318, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(1568, 84);
            System.Threading.Thread.Sleep(416);
            Console.Beep(392, 84);
            System.Threading.Thread.Sleep(416);
            Console.Beep(1046, 84);
            System.Threading.Thread.Sleep(292);
            Console.Beep(784, 84);
            System.Threading.Thread.Sleep(292);
            Console.Beep(659, 84);
            System.Threading.Thread.Sleep(292);
            Console.Beep(880, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(988, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(932, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(880, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(784, 84);
            System.Threading.Thread.Sleep(84);
            Console.Beep(1318, 84);
            System.Threading.Thread.Sleep(84);
            Console.Beep(1568, 84);
            System.Threading.Thread.Sleep(84);
            Console.Beep(1760, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(1396, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1568, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(1318, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(1046, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1174, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(988, 84);
            System.Threading.Thread.Sleep(292);
            Console.Beep(1046, 84);
            System.Threading.Thread.Sleep(292);
            Console.Beep(784, 84);
            System.Threading.Thread.Sleep(292);
            Console.Beep(659, 84);
            System.Threading.Thread.Sleep(292);
            Console.Beep(880, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(988, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(932, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(880, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(784, 84);
            System.Threading.Thread.Sleep(84);
            Console.Beep(1318, 84);
            System.Threading.Thread.Sleep(84);
            Console.Beep(1568, 84);
            System.Threading.Thread.Sleep(84);
            Console.Beep(1760, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(1396, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1568, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(1318, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(1046, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1174, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(988, 84);
            System.Threading.Thread.Sleep(292);
            Console.Beep(261, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(1568, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1480, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1396, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1244, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(523, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1318, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(349, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(831, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(880, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1046, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(523, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(880, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1046, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1174, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(261, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(1568, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1480, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1396, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1244, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(392, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(1318, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(2092, 84);
            System.Threading.Thread.Sleep(166);
            Console.Beep(2092, 84);
            System.Threading.Thread.Sleep(42);
            Console.Beep(2092, 84);        
    }

    public static void LongMario()
    {
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(416);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(416);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(659, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(988, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(932, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1760, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(988, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(659, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(988, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(932, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1760, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(988, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(261, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1480, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1244, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(831, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(261, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1480, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1244, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(2092, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(2092, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(2092, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(261, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1480, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1244, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(831, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(261, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1244, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(261, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(261, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1480, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1244, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(831, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(261, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1480, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1244, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(2092, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(2092, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(2092, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(261, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1480, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1244, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(831, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(261, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1244, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(261, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(196, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(792);
        Console.Beep(196, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(196, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(416);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(416);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(659, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(988, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(932, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1760, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(988, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(659, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(988, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(932, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1760, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(988, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(831, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(988, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1760, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1760, 42);
        Console.Beep(349, 42);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1760, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1568, 84);
        Console.Beep(494, 84);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(831, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(988, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(261, 84);
        System.Threading.Thread.Sleep(416);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(831, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(988, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1760, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1760, 42);
        Console.Beep(349, 42);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1760, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1568, 84);
        Console.Beep(494, 84);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(831, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(988, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(261, 84);
        System.Threading.Thread.Sleep(416);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(196, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(416);
        Console.Beep(261, 84);
        System.Threading.Thread.Sleep(292);
        Console.Beep(196, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(196, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1568, 84);
        System.Threading.Thread.Sleep(416);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(416);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(831, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(988, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1760, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1760, 42);
        Console.Beep(349, 42);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1760, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1568, 84);
        Console.Beep(494, 84);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(784, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(831, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(880, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(523, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(349, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(988, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(42);
        Console.Beep(1396, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1318, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1174, 84);
        System.Threading.Thread.Sleep(84);
        Console.Beep(1046, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(392, 84);
        System.Threading.Thread.Sleep(166);
        Console.Beep(261, 84);
        System.Threading.Thread.Sleep(166);
          

    }

    public  void WinnerBeep()
    {
        for (int i = 200; i < 2000; i += 100)
            System.Console.Beep(i, 50);
    }

    public  void StartShort()
    {
        t = new Thread(new ThreadStart(ShortMario));
        t.Start();

    }

    public  void StartLong()
    {
         t = new Thread(new ThreadStart(LongMario));
        t.Start();
    }

    public  void StartWinner()
    {
         t = new Thread(new ThreadStart(WinnerBeep));
        t.Start();
    }
    public  void ShutUP()
    {
        try
        {
            t.Abort();
        }
        catch (Exception)
        { }
    }
}